### ISSUE TITLE
option 4 about CMakeList

### ISSUE THREAD

**Issue by liu-xunnn** [LLNL/pLiner#14]
`echo "add_subdirectory(pLiner/clang-tool)" >> CMakeLists.txt`
`cp pLiner/clang-tool/CMakeLists.txt-insource CMakeLists`

I can't understand this two lines of code. 
I don't use the second line of code ,and pLiner is built suscessfully.
but some lib error about clang occurs.it leads to fail of tests excep region-trans.

**Comment by doloresmiao** [comment]
The original purpose of these two lines is to add pLiner to the source tree of Clang/LLVM, so that when you (incrementally or not) build Clang/LLVM again, it will also build pLiner.

Though it is indeed strange that `CMakeLists.txt` gets appended, and then followed by an overwrite. I will take a look into it and get back to you soon. Thanks!

**Comment by liu-xunnn** [comment]
I guess I might have added .txt at the end of the second line of code，so the CMakeLists.txt was overwritten. I will try again.

Another fact is that if I use option 4,the built llvm uses about 100G of space. So disk space is very tight. 

Thank you for your patience!

**Comment by doloresmiao** [comment]
Now I know what the problem iss: use `cp pLiner/clang-tool/CMakeLists.txt-insource pLiner/CMakeLists.txt` instead.

Other errors can be solved by `apt-get` the right packages.

I will update the `README.md` accordingly.

**Comment by liu-xunnn** [comment]
Excellent！
